/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javazoom.jl.player.Player;


public class Alarm_Clock extends javax.swing.JFrame {

    String sound,title;
    FileInputStream fileInputStream;
    BufferedInputStream bufferedInputStream;
    Player player;
    long all;
    String hours,hh,mm;
    String hourAlarm,minuteAlarm;
    
    public Alarm_Clock() {
        initComponents();
        
        Thread t = new Thread ();
        t.start();
            Calendar c =Calendar.getInstance();
            SimpleDateFormat  simpleDateFormat1 = new SimpleDateFormat("hh");
            SimpleDateFormat  simpleDateFormat2 = new SimpleDateFormat("mm");
            Date date = c.getTime();
            hh = simpleDateFormat1.format(date);
            mm = simpleDateFormat2.format(date);
            HourComboBox.setSelectedItem(hh);
            MinComboBox.setSelectedItem(mm);
            
    }
     public void chooseSong(){
        
        JFileChooser jfc = new JFileChooser();
        int soundINT = jfc.showOpenDialog(null);
        if(soundINT == JFileChooser.APPROVE_OPTION){
            File alarmMusic = jfc.getSelectedFile();
            sound = alarmMusic.getAbsolutePath();
            title = jfc.getSelectedFile().getName();
            System.out.println(title);
        }
        else if (soundINT == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null,"Choose Music!!!");
        }
    }
     
        public void startAlarm(){
        try{
            
            fileInputStream = new FileInputStream(sound);
            bufferedInputStream = new BufferedInputStream(fileInputStream);
            player = new Player (bufferedInputStream);
            all = fileInputStream.available();
            new Thread(){
                @Override
                public void run(){
                    try{
                        player.play();
                    }catch (Exception e){
                        
                    }
                }
            }.start();
            
            
        }catch(Exception e){
            
        }
    }
        
         public void alarmTime(final int hour , final int minute){
        Thread t = new Thread(){
            @Override
            public void run(){
                int time = 0;
                while (time==0){
                    Calendar c = Calendar.getInstance();
                    int h = c.get(Calendar.HOUR);
                    int m = c.get(Calendar.MINUTE);
                    if(hour == h && minute == m){
                     startAlarm();
                     JOptionPane.showMessageDialog(null,"ALARM!!!");
                     int stop = JOptionPane.showConfirmDialog(null,"STOP ALARM","",JOptionPane.YES_NO_OPTION);
                     if(stop == JOptionPane.YES_OPTION){
                         stopAlarm();
                         break;
                     }
                     
                    }
                }
            }
        };t.start();
    }

      public void stopAlarm(){
        if(player != null){
            player.close();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HourLabel = new javax.swing.JLabel();
        MinLabel = new javax.swing.JLabel();
        MinComboBox = new javax.swing.JComboBox<>();
        HourComboBox = new javax.swing.JComboBox<>();
        RingButton = new javax.swing.JButton();
        SetAlarm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MusicName = new javax.swing.JLabel();
        CLOCK = new javax.swing.JLabel();
        Listen = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 3));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("      Alarm Clock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        HourLabel.setBackground(new java.awt.Color(0, 0, 0));
        HourLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        HourLabel.setForeground(new java.awt.Color(255, 255, 255));
        HourLabel.setText(" Hour");
        HourLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));

        MinLabel.setBackground(new java.awt.Color(0, 0, 0));
        MinLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        MinLabel.setForeground(new java.awt.Color(255, 255, 255));
        MinLabel.setText("  Min");
        MinLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));

        MinComboBox.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        MinComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        MinComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinComboBoxActionPerformed(evt);
            }
        });

        HourComboBox.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        HourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        HourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourComboBoxActionPerformed(evt);
            }
        });

        RingButton.setBackground(new java.awt.Color(153, 153, 153));
        RingButton.setFont(new java.awt.Font("Arial", 3, 27)); // NOI18N
        RingButton.setForeground(new java.awt.Color(153, 0, 153));
        RingButton.setText("Set Music");
        RingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RingButtonActionPerformed(evt);
            }
        });

        SetAlarm.setBackground(new java.awt.Color(153, 153, 153));
        SetAlarm.setFont(new java.awt.Font("Arial", 3, 27)); // NOI18N
        SetAlarm.setForeground(new java.awt.Color(153, 0, 153));
        SetAlarm.setText("Set Alarm");
        SetAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetAlarmActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" :");

        MusicName.setBackground(new java.awt.Color(0, 0, 0));
        MusicName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        MusicName.setForeground(new java.awt.Color(255, 255, 255));

        CLOCK.setForeground(new java.awt.Color(255, 255, 255));

        Listen.setBackground(new java.awt.Color(153, 153, 153));
        Listen.setFont(new java.awt.Font("Arial", 3, 27)); // NOI18N
        Listen.setForeground(new java.awt.Color(153, 0, 153));
        Listen.setText("Listen");
        Listen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HourComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(378, Short.MAX_VALUE)
                        .addComponent(CLOCK)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(MusicName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(SetAlarm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(RingButton)
                        .addGap(31, 31, 31)
                        .addComponent(Listen, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MinComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(CLOCK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MusicName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Listen)
                    .addComponent(RingButton))
                .addGap(23, 23, 23)
                .addComponent(SetAlarm)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, 355));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinComboBoxActionPerformed

    private void HourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourComboBoxActionPerformed

    private void RingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RingButtonActionPerformed
        chooseSong();
        if(!sound.equals(null)){
            MusicName.setText("Alarm Music :" +title);
        }
       
    }//GEN-LAST:event_RingButtonActionPerformed

    private void SetAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetAlarmActionPerformed
       hourAlarm = HourComboBox.getSelectedItem().toString();
       minuteAlarm = MinComboBox.getSelectedItem().toString();
       if(MusicName.getText() != ""){
           String alarmClock = hourAlarm +":" +minuteAlarm;
           System.out.println(alarmClock);
           alarmTime(Integer.valueOf(hourAlarm),Integer.valueOf(minuteAlarm));
       }
       
       else{
           JOptionPane.showMessageDialog(null,"No music set ","warning!!",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_SetAlarmActionPerformed

    private void ListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListenActionPerformed
        if(Listen.getText().equals("Listen")){
            startAlarm();
           Listen.setText("Stop");
            SetAlarm.setEnabled(true);
        }
        else if (Listen.getText().equals("Stop")){
            Listen.setText("Listen");
            SetAlarm.setEnabled(true);
        }
    }//GEN-LAST:event_ListenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alarm_Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alarm_Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alarm_Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alarm_Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Alarm_Clock().setVisible(true);
            }
        });
    }
    public void run(){
        while (true){
            Calendar c =Calendar.getInstance();
            SimpleDateFormat  simpleDateFormat = new SimpleDateFormat("hh:mm:ss");
            Date date = c.getTime();
            hours = simpleDateFormat.format(date);
            
            CLOCK.setText(hours);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOCK;
    private javax.swing.JComboBox<String> HourComboBox;
    private javax.swing.JLabel HourLabel;
    private javax.swing.JButton Listen;
    private javax.swing.JComboBox<String> MinComboBox;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JLabel MusicName;
    private javax.swing.JButton RingButton;
    private javax.swing.JButton SetAlarm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
