/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock;

import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;


public class Main_frame extends javax.swing.JFrame {

    
    
    public Main_frame() {
        initComponents();
        
        Thread t = new Thread()
                {
                    @Override
                    public void run()
                {
                    while(true)
                {
                    Format f = new SimpleDateFormat(" hh : mm : ss aa");
                    
                    String timestring = f.format(new Date()).toString();
                    
                    time_label.setText(timestring);
                    
                    Calendar c = Calendar.getInstance();
                    f = new SimpleDateFormat(" dd - MMM - yyyy ");
                    
                    String  datestring= f.format(new Date()).toString();
                    
                    date_label.setText(datestring);
                    
                    try
                {
                   
                    Thread.sleep(1);
                                         
                     
                }
                    catch(Exception e)
                {
                    
                }   
                }
                }
                };
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Alarm = new javax.swing.JButton();
        Counter = new javax.swing.JButton();
        Timer = new javax.swing.JButton();
        Stop_Watch = new javax.swing.JButton();
        time_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Alarm.setBackground(new java.awt.Color(153, 255, 255));
        Alarm.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Alarm.setText("Alarm");
        Alarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlarmActionPerformed(evt);
            }
        });
        getContentPane().add(Alarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 50));

        Counter.setBackground(new java.awt.Color(153, 255, 255));
        Counter.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Counter.setText("Counter");
        Counter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CounterActionPerformed(evt);
            }
        });
        getContentPane().add(Counter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 120, 50));

        Timer.setBackground(new java.awt.Color(153, 255, 255));
        Timer.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Timer.setText("Timer");
        Timer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimerActionPerformed(evt);
            }
        });
        getContentPane().add(Timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 50));

        Stop_Watch.setBackground(new java.awt.Color(153, 255, 255));
        Stop_Watch.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Stop_Watch.setText("Stop Watch");
        Stop_Watch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stop_WatchActionPerformed(evt);
            }
        });
        getContentPane().add(Stop_Watch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 50));

        time_label.setFont(new java.awt.Font("Arial", 1, 55)); // NOI18N
        time_label.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        date_label.setFont(new java.awt.Font("Arial", 0, 38)); // NOI18N
        date_label.setForeground(new java.awt.Color(255, 255, 255));
        date_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 310, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock/valentin-muller-bWtd1ZyEy6w-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Stop_WatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stop_WatchActionPerformed
        new stopwatch1().setVisible(true);
    }//GEN-LAST:event_Stop_WatchActionPerformed

    private void AlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlarmActionPerformed
       new Alarm_Clock().setVisible(true);
    }//GEN-LAST:event_AlarmActionPerformed

    private void TimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimerActionPerformed
        new Clock_Timer().setVisible(true);
    }//GEN-LAST:event_TimerActionPerformed

    private void CounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CounterActionPerformed
        new Counter().setVisible(true);
    }//GEN-LAST:event_CounterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alarm;
    private javax.swing.JButton Counter;
    private javax.swing.JButton Stop_Watch;
    private javax.swing.JButton Timer;
    private javax.swing.JLabel date_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel time_label;
    // End of variables declaration//GEN-END:variables
}
