/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock;

import static java.lang.Thread.sleep;


public class stopwatch1 extends javax.swing.JFrame {

   static int milliseconds = 00; 
    static int seconds = 00; 
    static int hours = 00; 
    static int minutes = 00; 
    static boolean state= true;
    
    
    public stopwatch1() {
        initComponents();
        turnoff();
    }
    private void turnoff()
    {
        Lap1.setEnabled(false);
        Lap2.setEnabled(false);
        Lap3.setEnabled(false);
        Lap4.setEnabled(false);
      
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        milisec = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hour = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        milisec1 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Lap2 = new javax.swing.JButton();
        Lap1 = new javax.swing.JButton();
        Lap4 = new javax.swing.JButton();
        Lap3 = new javax.swing.JButton();
        Lap1Label = new javax.swing.JLabel();
        Lap1Label2 = new javax.swing.JLabel();
        Lap1Label3 = new javax.swing.JLabel();
        Lap1Label4 = new javax.swing.JLabel();
        Cont = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        milisec.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        getContentPane().add(milisec, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 437, -1, 33));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 3));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     Stop Watch");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        hour.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        hour.setForeground(new java.awt.Color(255, 255, 255));
        hour.setText("00");

        min.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setText("00");

        sec.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        sec.setForeground(new java.awt.Color(255, 255, 255));
        sec.setText("00");

        milisec1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        milisec1.setForeground(new java.awt.Color(255, 255, 255));
        milisec1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milisec1.setText("00");

        ResetButton.setBackground(new java.awt.Color(153, 153, 153));
        ResetButton.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(153, 0, 204));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        StartButton.setBackground(new java.awt.Color(153, 153, 153));
        StartButton.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        StartButton.setForeground(new java.awt.Color(255, 0, 153));
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        StopButton.setBackground(new java.awt.Color(153, 153, 153));
        StopButton.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        StopButton.setForeground(new java.awt.Color(255, 0, 0));
        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hour");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Min");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sec");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Milisec");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 2));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lap2.setBackground(new java.awt.Color(0, 0, 0));
        Lap2.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Lap2.setForeground(new java.awt.Color(255, 255, 255));
        Lap2.setText(" Lap 2");
        Lap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lap2ActionPerformed(evt);
            }
        });
        jPanel4.add(Lap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 35));

        Lap1.setBackground(new java.awt.Color(0, 0, 0));
        Lap1.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Lap1.setForeground(new java.awt.Color(255, 255, 255));
        Lap1.setText(" Lap 1");
        Lap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lap1ActionPerformed(evt);
            }
        });
        jPanel4.add(Lap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 35));

        Lap4.setBackground(new java.awt.Color(0, 0, 0));
        Lap4.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Lap4.setForeground(new java.awt.Color(255, 255, 255));
        Lap4.setText(" Lap 4");
        Lap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lap4ActionPerformed(evt);
            }
        });
        jPanel4.add(Lap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 35));

        Lap3.setBackground(new java.awt.Color(0, 0, 0));
        Lap3.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Lap3.setForeground(new java.awt.Color(255, 255, 255));
        Lap3.setText(" Lap 3");
        Lap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lap3ActionPerformed(evt);
            }
        });
        jPanel4.add(Lap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 35));

        Lap1Label.setBackground(new java.awt.Color(0, 0, 0));
        Lap1Label.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        Lap1Label.setForeground(new java.awt.Color(255, 255, 255));
        Lap1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lap1Label.setText("00:00:00:000");
        Lap1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102)));
        jPanel4.add(Lap1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 250, 30));

        Lap1Label2.setBackground(new java.awt.Color(0, 0, 0));
        Lap1Label2.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        Lap1Label2.setForeground(new java.awt.Color(255, 255, 255));
        Lap1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lap1Label2.setText("00:00:00:000");
        Lap1Label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102)));
        jPanel4.add(Lap1Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, 30));

        Lap1Label3.setBackground(new java.awt.Color(0, 0, 0));
        Lap1Label3.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        Lap1Label3.setForeground(new java.awt.Color(255, 255, 255));
        Lap1Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lap1Label3.setText("00:00:00:000");
        Lap1Label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102)));
        jPanel4.add(Lap1Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        Lap1Label4.setBackground(new java.awt.Color(0, 0, 0));
        Lap1Label4.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        Lap1Label4.setForeground(new java.awt.Color(255, 255, 255));
        Lap1Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lap1Label4.setText("00:00:00:000");
        Lap1Label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102)));
        jPanel4.add(Lap1Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 250, 30));

        Cont.setBackground(new java.awt.Color(153, 153, 153));
        Cont.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Cont.setForeground(new java.awt.Color(153, 0, 0));
        Cont.setText("Continue");
        Cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(47, 47, 47))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ResetButton)
                                    .addGap(35, 35, 35)
                                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(milisec1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(Cont, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milisec1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Cont, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
         
          Lap1.setEnabled(true);
          state = true;
        Thread t = new Thread(){
            @Override
            public void run(){
                
               while(true){
                   if (state == true)
                   {
                       try{
                           sleep(1);
                           if(milliseconds > 1000)
                           {
                               milliseconds = 00;
                               seconds++;
                               
                           }
                           if(seconds>60)
                           {
                               milliseconds = 00 ;
                               seconds = 00 ;
                               minutes ++ ;
                               
                           }
                           if(minutes>60)
                           {
                               milliseconds = 00;
                               seconds=00;
                               minutes=00;
                               hours++;
                               
                           }
                           
                           milisec1.setText(""+ milliseconds);
                           milliseconds++;
                           sec.setText(""+ seconds);
                           min.setText(""+ minutes);
                           hour.setText(""+ hours);
                        
                           
                       }catch(Exception e){
                           
                       }
                   }
                   else{
                       break;
                   }
               }
        }
        }; 
        
        t.start();
    }//GEN-LAST:event_StartButtonActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
       // turnoff();
        state = false;
        Lap1.setEnabled(true);
        Lap2.setEnabled(true);
       Lap3.setEnabled(true);
       Lap4.setEnabled(true);
       
        
    }//GEN-LAST:event_StopButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
         state = false;
     milliseconds = 0; 
     seconds = 0; 
     hours = 0; 
     minutes = 0;
     
     hour.setText("00 :");
     min.setText("00 ");
     sec.setText("00 ");
     milisec1.setText("00");
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      Lap1.setVisible(true);
      Lap2.setVisible(false);
      Lap3.setVisible(false);
      Lap4.setVisible(false);
      
      Lap1Label.setVisible(false);
      Lap1Label2.setVisible(false);
      Lap1Label3.setVisible(false);
      Lap1Label4.setVisible(false);
   
      Cont.setEnabled(false);
      Lap1.setEnabled(true);
      Lap2.setEnabled(true);
       Lap3.setEnabled(true);
       Lap4.setEnabled(true);

      
      
    }//GEN-LAST:event_formWindowActivated

    private void ContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContActionPerformed
       Lap1.setEnabled(true);
       Lap2.setEnabled(true);
       Lap3.setEnabled(true);
       Lap4.setEnabled(true);
       
       state = true;     
        Thread t = new Thread(){
            @Override
            public void run(){
                
               while(true){
                   if (state == true)
                   {
                       try{
                           sleep(1);
                           if(milliseconds > 1000)
                           {
                               milliseconds = 00;
                               seconds++;
                               
                           }
                           if(seconds>60)
                           {
                               milliseconds = 00 ;
                               seconds = 00 ;
                               minutes ++ ;
                               
                           }
                           if(minutes>60)
                           {
                               milliseconds = 00;
                               seconds=00;
                               minutes=00;
                               hours++;
                               
                           }
                           
                           milisec1.setText(""+ milliseconds);
                           milliseconds++;
                           sec.setText(""+ seconds);
                           min.setText(""+ minutes);
                           hour.setText(""+ hours);
                        
                           
                       }catch(Exception e){
                           
                       }
                   }
                   else{
                       break;
                   }
               }
        }
        }; 
        
        t.start();
    }//GEN-LAST:event_ContActionPerformed

    private void Lap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lap1ActionPerformed
      
    
      Lap1Label.setVisible(true);
       Lap2.setVisible(true);
       Lap2.setEnabled(true);
       Lap1Label.setText(hour.getText()+":"+min.getText()+":"+sec.getText()+":"+milisec1.getText());
      
    }//GEN-LAST:event_Lap1ActionPerformed

    private void Lap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lap2ActionPerformed
           Lap1Label2.setVisible(true);
       Lap3.setVisible(true);
       Lap3.setEnabled(true);
        Lap1Label2.setText(hour.getText()+":"+min.getText()+":"+sec.getText()+":"+milisec1.getText());
      
    }//GEN-LAST:event_Lap2ActionPerformed

    private void Lap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lap3ActionPerformed
         Lap1Label3.setVisible(true);
       Lap4.setVisible(true);
       Lap4.setEnabled(true);
        Lap1Label3.setText(hour.getText()+":"+min.getText()+":"+sec.getText()+":"+milisec1.getText());
    }//GEN-LAST:event_Lap3ActionPerformed

    private void Lap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lap4ActionPerformed
         Lap1Label4.setVisible(true);
       Lap4.setVisible(true);
       Lap4.setEnabled(true);
        Lap1Label4.setText(hour.getText()+":"+min.getText()+":"+sec.getText()+":"+milisec1.getText());
    }//GEN-LAST:event_Lap4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stopwatch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stopwatch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stopwatch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stopwatch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stopwatch1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cont;
    private javax.swing.JButton Lap1;
    private javax.swing.JLabel Lap1Label;
    private javax.swing.JLabel Lap1Label2;
    private javax.swing.JLabel Lap1Label3;
    private javax.swing.JLabel Lap1Label4;
    private javax.swing.JButton Lap2;
    private javax.swing.JButton Lap3;
    private javax.swing.JButton Lap4;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton StopButton;
    private javax.swing.JLabel hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel milisec;
    private javax.swing.JLabel milisec1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel sec;
    // End of variables declaration//GEN-END:variables
}
